ecommerce/cart/urls.py
from django.contrib import admin
from django.urls import path, include
from cart import views
app_name ="cart"

urlpatterns = [
    path('cart/<n>',views.cart, name='cart'),
    path('cartview',views.cartview, name='cartview'),
    path('cart_remove/<n>',views.cart_remove, name='cart_remove'),
    path('full_remove/<n>',views.full_remove, name='full_remove'),
    path('orderform',views.orderform, name='orderform'),
    path('orderVIEW', views.orderview, name='orderview'),



]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('search/',include('search.urls')),
    path('cart/',include('cart.urls')),
]

ecommerce/search/urls.py
from django.contrib import admin
from django.urls import path,include
from search import views
app_name="search"
urlpatterns = [
    path('', views.search,name="search"),


]

ecommerce/shop/urls.py
from django.contrib import admin
from django.urls import path,include
from shop import views
from django.conf import settings
from django.conf.urls.static import static
app_name="shop"
urlpatterns = [
    path('',views.allcategories,name="allcat"),
    path('allprod/<p>',views.allproducts,name="allprod"),
    path('details/<c>',views.details,name='details'),
    path('register',views.register,name="register"),
    path('login', views.user_login, name="login"),
    path('logout', views.logout_view, name="logout")
]


if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecommerce/cart/models.py
from django.db import models
from django.contrib.auth.models import User
from shop.models import Product
# Create your models here.

class Cart(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    date_added=models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.product.name

    def subtotal(self):
        return self.quantity*self.product.price

class Order(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    no_of_items=models.IntegerField()
    address=models.TextField()
    phone=models.IntegerField()
    order_status=models.CharField(max_length=20,default="pending")
    delivery_status=models.CharField(max_length=20,default="pending")
    order_date=models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.user.username
class Account(models.Model):
    acctnum=models.CharField(max_length=20)
    accttype=models.CharField(max_length=20)
    amount=models.IntegerField()
    def __str__(self):
        return self.acctnum

ecommerce/search/models.py
from django.db import models

# Create your models here.

ecommerce/cart/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect
from shop.models import Product
from cart.models import Cart,Account,Order
from django.db import transaction
from django.contrib import messages

@login_required
def cartview(request):
    u = request.user
    try:
        cart_items = Cart.objects.filter(user=u)
        total = sum(item.quantity * item.product.price for item in cart_items)
    except Cart.DoesNotExist:
        cart_items = []
        total = 0

    return render(request, 'cartview.html', {'c': cart_items, 'total': total})

@login_required
# Create your views here.
def cart(request, n):
    p = Product.objects.get(name=n)
    u = request.user
    try:
        cart = Cart.objects.get(user=u, product=p)
        if (p.stock > 0):
            cart.quantity += 1
            cart.save()
            p.stock -= 1
            p.save()

    except:
        if (p.stock > 0):
            cart = Cart.objects.create(product=p, user=u, quantity=1)
            cart.save()
            p.stock-=1
            p.save()

    return redirect('cart:cartview')
@login_required
def cart_remove(request, n):
    p = Product.objects.get(name=n)
    u = request.user
    try:
        cart = Cart.objects.get(user=u, product=p)
        if (cart.quantity >1):
            cart.quantity -= 1
            cart.save()
            p.stock += 1
            p.save()

        else:
            cart.delete()
            p.stock += 1
            p.save()

    except:
       pass

    return redirect('cart:cartview')
@login_required
def full_remove(request, n):
    p = Product.objects.get(name=n)
    u = request.user
    try:
        cart = Cart.objects.get(user=u, product=p)
        cart.delete()
        p.stock += cart.quantity
        p.save()
    except:
       pass

    return cartview(request)
@login_required
def orderform(request):
    if request.method == "POST":
        a = request.POST['a']
        ph = request.POST['ph']
        an = request.POST['an']

        u = request.user
        cart = Cart.objects.filter(user=u)
        total = 0
        for i in cart:
            total += i.quantity * i.product.price
        try:
            ac = Account.objects.get(acctnum=an)  # to retrieve the acctobject
            if ac.amount >= total:
                ac.amount = ac.amount - total
                ac.save()
                for i in cart:
                    o = Order.objects.create(user=u, product=i.product, address=a, phone=ph, no_of_items=i.quantity, order_status="paid")
                    o.save()
                cart.delete()
                return redirect('cart:orderview')

            else:
                msg = "Insufficient amount, you can't place an order"
                return render(request, "orderdetail.html", {'msg': msg})
        except Account.DoesNotExist:
            pass

    return render(request, 'orderform.html')
@login_required
def orderview(request):
    u=request.user
    o=Order.objects.filter(user=u)
    return render(request,'orderview.html',{'o':o})

ecommerce/search/views.py
from django.db.models import Q
from django.shortcuts import render

from shop.models import Product


# Create your views here.
def search(request):
    query=""
    products=None
    if (request.method=="POST"):
        query=request.POST['q']
        products=Product.objects.filter(Q(name__icontains=query)| Q(desc__icontains=query))
        return render(request,"search.html",{"query":query,"p":products})

ecommerce/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Zilla+Slab:ital,wght@1,300&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <style>
        body {
            background-image: url('{% static "images/multiplayer-game-3840-x-2160-wallpaper-eey6beng16f9onra.jpg" %}');
            background-size: cover;
            background-repeat: no-repeat;
            margin: 0;
            padding: 0;
            font-family: 'Zilla Slab', sans-serif;
            color: white;
        }

        .navbar {
            background-color: transparent;
            padding: 10px;
        }

        .navbar-brand img {
            border-radius: 50%;
            margin-right: 10px;
        }

        .navbar-nav {
            margin-left: auto;
        }

        .nav-item {
            margin-right: 10px;
        }

        .form-control {
            background-color: rgba(255, 255, 255, 0.7);
        }

        .nm {
            position: absolute;
            top: 20px;
            color: white;
            right: 20px;
        }

        .foot {
            background-color: #343a40;
            text-align: center;
            padding: 10px;
            position: fixed;
            width: 100%;
            bottom: 0;
            height: 34px;
        }

        #h66 {
            font-size: 10px;
            position: relative;
            top: -5px;
            color: white;
        }
        #nnmm{
        position:relative;
        right:1550px;
        top:3px;
        }
        #icon{
        position:relative;
        top:7px;
        left:500px;

        }
    </style>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid" id="nb">
        <a class="navbar-brand" href="{% url 'shop:allcat'%}">
            <img src="{% static 'images/355114658_566576692298717_6946484188984313951_n.jpg' %}" alt="Logo" width="40px;" height="40px;">
            MoonStore
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'shop:allcat'%}">Home</a>
                </li>
                {% if user.is_authenticated %}
                <a href="{% url 'cart:cartview'%}" style="color:white;" id="icon">cart</a>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            All-Categories
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            {% for i in links %}
                                <li><a class="dropdown-item" href="{% url 'shop:allprod' i.name %}">{{i.name}}</a></li>
                            {% endfor %}
                            <li><a class="dropdown-item" href="#">Others</a></li>

                        </ul>
                    </li>
                {% endif %}
            </ul>
            <form class="d-flex" method="POST" action="{% url 'search:search'%}">
                {% csrf_token %}
                <input class="form-control me-2" name="q" type="search" placeholder="Search" aria-label="Search">
                <div>
                    <button class="btn btn-outline-primary" type="submit">Search</button>
                </div>
            </form>
            <div class="nm">
                {% if user.is_authenticated %}
                    <p id="nnmm">Welcome, {{user.username}}!</p>
                {% else %}
                    <p>Guest</p>
                {% endif %}
            </div>
        </div>
    </div>
</nav>
{% block content %}
{% endblock %}
<footer>
    <div class="foot">
        <center>
            <p><i id="h66" class="fa-regular fa-copyright">MoonStore pvt Ltd.All Rights reserved</i></p>
        </center>
    </div>
</footer>
</body>
</html>

ecommerce/templates/cartview.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<style>
    .table-bordered {
        border-color: black;
        border-width: 3px;
    }
    .cart-icons a {
        display: block;
        margin-bottom: 5px;
    }
    .checkout-table {
        margin-top: 20px;
        position: absolute;
        left: 900px;
    }
    #ci {
        position: absolute;
        left: 50px;
        width: 40px;
        top: 130px;
    }
</style>

<div class="container">
    <div class="row">
        <h4 class="text-center">Your cart</h4>
        <div class="col-12">
            <div class="row">
                <div class="col-6">
                    <table class="table table-bordered" id="ci">
                        <tr>
                            <th colspan="7">Cart Items</th>
                        </tr>
                        {% for item in c %}
                            <tr>
                                <td>
                                    <img src="{{ item.product.image.url }}" height="200px;" width="200px;">
                                </td>
                                <td style="font-size: 18px; font-family: Times, serif;">{{ item.product.name }}</td>
                                <td><h6>Product ID: {{ item.product.id }}</h6></td>
                                <td><h6>Price: {{ item.product.price }}</h6></td>
                                <td><h6>Quantity: {{ item.quantity }}*{{ item.product.price }}</h6></td>
                                <td>Total: {{ item.subtotal }}</td>
                                <td class="cart-icons">
                                    {% if item.quantity < item.product.stock %}
                                    <a href="{% url 'cart:cart' n=item.product.name %}" class="btn btn-info" title="Add one more of this item to your cart"><i class="fa-solid fa-circle-plus"></i></a>
                                    <a href="{% url 'cart:cart_remove' n=item.product.name %}" class="btn btn-warning" title="remove one  of this item to your cart"><i class="fa-solid fa-circle-minus"></i></a>
                                    <a href="{% url 'cart:full_remove' n=item.product.name %}" class="btn btn-danger"title="remove this item from your cart"><i class="fa-solid fa-trash"></i></a>
                        {% else %}
                                     <a href="{% url 'cart:cart_remove' n=item.product.name %}" class="btn btn-warning" title="remove one  of this item to your cart"><i class="fa-solid fa-circle-minus"></i></a>
                                    <a href="{% url 'cart:full_remove' n=item.product.name %}" class="btn btn-danger"title="remove this item from your cart"><i class="fa-solid fa-trash"></i></a></td></tr>
                                    {% endif %}
                        {% endfor %}
                    </table>
                </div>

                <div class="col-6 checkout-table">
                    <table class="table table-bordered">
                        <tr>
                            <th colspan="4">Checkout</th></tr>
                        <tr><td>TOTAL : {{total}}</td></tr>
                        <td>
                            <a href="{% url 'cart:orderform' %}" class="btn btn-primary">Place order</a>
                            <a href="" class="btn btn-primary">Continue shopping</a></td>

                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

ecommerce/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<div class="banner">
    <img src="{% static 'images/purple-gaming-sfiq72g5kksu8khe.jpg'%}" alt="Banner Image" class="img-fluid"
        style="width: 1999px; max-height: 500px;">

</div>
<br>
<div class="container-fluid section" style="background-color: #d8b4fe; text-align: center; padding: 20px;">
    <h1 class="quote" style="font-family: 'YourFont', sans-serif; color:black;">"Hey Gamers"</h1>
    <p class="description" style="font-family: 'YourFont', sans-serif; color: black;">
        Welcome to our enchanting world of hand embroidery, where craftsmanship meets creativity. Our ecommerce website
        invites you to explore a curated collection of exquisite hand-embroidered treasures that transcend mere fabric
        and thread. Immerse yourself in the delicate dance of needle and fiber, where every stitch tells a story of
        passion and precision.
    </p>
</div>

<br>
<div class="container mt-5">
    <div class="row justify-content-center">
        {% for category in c %}
        <div class="col-md-4 product-card">
            <div class="card mx-auto custom-card" style="width: 18rem; margin-bottom: 20px;">
                <img src="{{ category.image.url }}" class="card-img-top img-fluid" alt="{{ category.name }}">
                <div class="card-body">
                    <h5 class="card-title text-center" style="color: black;">{{ category.name }}</h5>
                    <p class="card-text text-center" style="color: black;">{{ category.desc }}</p>
                    <a href="{% url 'shop:allprod' category.name %}"
                        class="btn btn-success d-block mx-auto" style="background-color: violet;">Products</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

ecommerce/templates/details.html
{% extends 'base.html' %}
{% block content %}

<style>
    .imgg {
        position: absolute;
        left: 200px;
        top: 90px;
    }

    .desc {
        position: absolute;
        left: 650px;
        width: 1000px;
        top: 90px;
        color: black;  /* Set text color to black */
    }

    .btn-primary {
        background-color: #d8b4fe;  /* Change button color to violet */
        border-color: #d8b4fe;  /* Change button border color to violet */
    }
</style>

<div class="row">
    <div class="imgg">
        <img src="{{ p.image.url }}" height="400px" width="400px">
    </div>
    <div class="desc">
        <h3>{{ p.name }}</h3>
        <p class="mt-2 lh base" style="font-size: 22px;">{{ p.desc }}</p>
        <h2 class="mt-2">{{ p.price }}</h2>
        <h2 class="mt-3" style="font-size: 20px;">Stock left: {{ p.stock }}</h2>
        <a href="{% url 'cart:cart' n=p.name %}" class="btn btn-primary">ADD TO CART</a>
    </div>
</div>

{% endblock %}

ecommerce/templates/login.html
{% extends 'base.html'%}
{% block content %}




<style>
</style>
<body>
<h1>Login Page</h1>
<div class="logg">
<form  method="POST" enctype="multipart/form-data">
   {% csrf_token %}
  <div class="form-group">
    <label for="exampleInputEmail1">Username</label>
    <input type="text" class="form-control" name="u" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter your username">
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Password</label>
    <input type="password" class="form-control" name="p" id="exampleInputPassword1" placeholder="Enter Your Password">
  </div>
  <center>
  <div class=button2>
  <button type="submit" class="btn btn-primary">Login</button>
  </div>
  </center>
</form>
</div>
</body>

{% endblock %}

ecommerce/templates/orderdetails.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}

<center>
    <h3>Place Order</h3>

  <form method="POST" style="padding: 20px; width: 50%; margin: auto; background-color: #fff; border-radius: 8px; box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);">
    {% csrf_token %}
    <div class="mb-3">
      <label class="form-label">Address</label>
      <input type="text" class="form-control"  name="a" placeholder="Enter the address">
    </div>
    <div class="mb-3">
      <label class="form-label">Phone </label>
      <input type="number" class="form-control" name="ph" placeholder="Enter the phone number">
    </div>
    <div class="mb-3">
      <label class="form-label">Account Number</label>
      <input type="number" class="form-control" name="an" placeholder="Enter the account number">
    </div>
    <div class="mb-3">
      <input type="submit" class="form-control btn btn-danger">
    </div>
</form>

</center>
<br><br><br><br><br><br>
{% endblock %}

ecommerce/templates/orderform.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}

<center>
    <h3>Order please!!!</h3>

  <form method="POST" style="padding: 20px; width: 50%; margin: auto; background-color: #fff; border-radius: 8px; box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);">
    {% csrf_token %}
    <div class="mb-3">
      <label class="form-label">Address</label>
      <input type="text" class="form-control"  name="a" placeholder="Enter the address">
    </div>
    <div class="mb-3">
      <label class="form-label">Phone </label>
      <input type="number" class="form-control" name="ph" placeholder="Enter the phone number">
    </div>
    <div class="mb-3">
      <label class="form-label">Account Number</label>
      <input type="number" class="form-control" name="an" placeholder="Enter the account number">
    </div>
    <div class="mb-3">
      <input type="submit" class="form-control btn btn-danger">
    </div>
</form>

</center>
<br><br><br><br><br><br>
{% endblock %}

ecommerce/templates/orderview.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <table class="table">
        <thead>
            <tr>
                <th>Name of the Customer</th>
                <th>Product Name</th>
                <th>Product Price</th>
                <th>Delivery Address</th>
                <th>No. of Items</th>
                <th>Ordered On</th>
                <th>Delivery Status</th>
                <th>Product Image</th>
            </tr>
        </thead>
        <tbody>
            {% for i in o %}
                <tr>
                    <td>{{ user.username }}</td>
                    <td>{{ i.product.name }}</td>
                    <td>{{ i.product.price }}</td>
                    <td>{{ i.address }}</td>
                    <td>{{ i.no_of_items }}</td>
                    <td>{{ i.ordered_date }}</td>
                    <td style="color: #B7CAB4;">{{ i.delivery_status }}</td>
                    <td><img src="{{ i.product.image.url }}" height="100px" width="100px"></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

ecommerce/templates/product.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container-fluid">
    {% if c.image %}
        <img src="{{ c.image.url }}" height="900px;" width="100%">
    {% else %}
        <p>No image available</p>
    {% endif %}
</div>

<div id="coll" class="container-fluid" style="background-color:#E0115F;">
    <center>
        <h3 style="color: black;">{{ c.name }}</h3>
    </center>
    <p style="color: black;">{{ c.desc }}</p>
</div>

<div class="container-fluid">
    <div class="row">
        {% for i in p %}
            <div class="col-sm-4">
                <div class="card" style="width: 18rem;">
                    {% if i.image %}
                        <img src="{{ i.image.url }}" class="card-img-top" height="300px;" width="100%">
                    {% else %}
                        <p>No image available</p>
                    {% endif %}
                    <div class="card-body">
                        <h5 class="card-title" style="color: black;">{{ i.name }}</h5>
                        <h5 class="card-title" style="color: black;">{{ i.price }}</h5>
                        <p class="card-text" style="color: black;">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                        <a href="{% url 'shop:details' i.name %}" class="btn btn-primary" style="background-color: #E0115F; border-color: #E0115F; color: black;">Details</a>
                    </div>
                </div>
            </div>
            <br><br><br>
        {% endfor %}
    </div>
</div>
{% endblock %}

ecommerce/templates/register.html
{% extends 'base.html'%}
{% block content %}

<body style="background-color:yellow;">
<form method="POST" class="frm" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="form-group">
    <label>Username</label>
    <input type="text" class="form-control" name="u" placeholder="Enter Username">
  </div>
  <div class="form-group">
    <label >Password</label>
    <input type="password" class="form-control" name="p" placeholder="Password">
  </div>
      <div class="form-group">
    <label> Confirm password</label>
    <input type="password" class="form-control" name="c"  placeholder="ConfirmPassword">
  </div>
      <div class="form-group">
    <label>email</label>
    <input type="email" class="form-control" name="e" placeholder="Enter email">
  </div>
      <div class="form-group">
    <label>First Name</label>
    <input type="text" class="form-control" name="f"  placeholder="Enter Your firstname">
  </div>
      <div class="form-group">
    <label>Last Name</label>
    <input type="text" class="form-control" name="l" placeholder="Enter your Lastname">
  </div>


  <button type="submit" class="btn btn-primary">Submit</button>
</form>
</body>
{% endblock %}

ecommerce/templates/search.html
{% extends 'base.html'%}
{% load static %}
{% block content %}


<div id="coll" class="container-fluid" style="background-color:#E0115F;">
    <center>
    <h3>{{c.name}}</h3>
    </center>
    <p>{{c.desc}}</p>
</div>
<div class="container-fluid">
  <div class="row">
      {% if p %}
    {% for i in p %}
    <div class="col-sm-4">
<div class="card" style="width: 18rem;">
  <img src="{{ i.image.url}}" class="card-img-top" height="200px;"width="100%">
  <div class="card-body">
    <h5 class="card-title">{{ i.name }}</h5>
       <h5 class="card-title">{{ i.price }}</h5>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    <a href="{% url 'shop:details' i.name %}" class="btn btn-primary">Details</a>
  </div>
</div>

    </div>
    {% endfor %}
      {% else %}
      <h4>NO results found</h4>
      {% endif %}
  </div>
</div>
{% endblock %}